"""Sphinx configuration for AXIOMM documentation.

Pages are written in Markdown via myst-parser. The Python API reference
is auto-generated by sphinx-autoapi from the package source in
``src/axiomm`` — no manual ``automodule`` directives needed.

To build locally::

    pip install -e ".[dev,all,docs]"
    cd docs
    make html
    # open _build/html/index.html
"""

from __future__ import annotations

import os
import sys
from importlib.metadata import version as _pkg_version
from pathlib import Path

# Make the package importable for autoapi.
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "src"))


# -- Project information -----------------------------------------------------

project = "AXIOMM"
author = "Francesco Perrone"
copyright = f"2026, {author}"

try:
    release = _pkg_version("axiomm")
except Exception:  # pragma: no cover - first-build fallback
    release = "0.1.0.dev0"
version = release


# -- General configuration ---------------------------------------------------

extensions = [
    "myst_parser",
    "autoapi.extension",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
]

source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}

master_doc = "index"

# Exclude the development state, the spec, and the legacy prototype from
# the published docs — they belong to repo maintainers, not end users.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "dev/**",
    "specs/**",
]


# -- HTML output -------------------------------------------------------------

html_theme = "furo"
html_title = f"AXIOMM {release}"
html_static_path: list[str] = []  # empty for now; add _static when needed

html_theme_options = {
    "source_repository": "https://github.com/FrancescoPerrone/axiomm/",
    "source_branch": "main",
    "source_directory": "docs/",
}


# -- MyST (Markdown) ---------------------------------------------------------

myst_enable_extensions = [
    "deflist",
    "tasklist",
    "colon_fence",
    "dollarmath",      # $...$ for inline math
    "amsmath",         # \begin{align} ... \end{align}
    "fieldlist",
    "substitution",
]

myst_heading_anchors = 4  # add anchors to headings up to level 4


# -- Intersphinx -------------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "h5py": ("https://docs.h5py.org/en/stable/", None),
    "hyperspy": ("https://hyperspy.org/hyperspy-doc/current/", None),
}


# -- sphinx-autoapi ----------------------------------------------------------

autoapi_type = "python"
autoapi_dirs = [str(_REPO_ROOT / "src" / "axiomm")]
autoapi_root = "api"
autoapi_keep_files = False
autoapi_add_toctree_entry = True
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
    "imported-members",
]
# Don't tracebacks from optional-dep imports during autoapi discovery.
suppress_warnings = ["autoapi"]


# -- sphinx-copybutton -------------------------------------------------------

copybutton_prompt_text = r">>> |\$ "
copybutton_prompt_is_regexp = True


# -- Misc --------------------------------------------------------------------

# Nitpicky catches broken cross-references; useful while authoring.
nitpicky = False  # flip to True once references stabilise.
