"""Sphinx configuration for AXIOMM documentation.

Pages are written in Markdown via myst-parser. The Python API reference
is auto-generated by sphinx-autoapi from the package source in
``src/axiomm`` — no manual ``automodule`` directives needed.

To build locally::

    pip install -e ".[dev,all,docs]"
    cd docs
    make html
    # open _build/html/index.html
"""

from __future__ import annotations

import os
import sys
from importlib.metadata import version as _pkg_version
from pathlib import Path

# Make the package importable for autoapi.
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT / "src"))


# -- Project information -----------------------------------------------------

project = "AXIOMM"
author = "Francesco Perrone"
copyright = f"2026, {author}"

try:
    release = _pkg_version("axiomm")
except Exception:  # pragma: no cover - first-build fallback
    release = "0.1.0.dev0"
version = release


# -- General configuration ---------------------------------------------------

extensions = [
    "myst_parser",
    "autoapi.extension",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
]

source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}

master_doc = "index"

# Exclude the development state, the spec, and the legacy prototype from
# the published docs — they belong to repo maintainers, not end users.
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "dev/**",
    "specs/**",
]


# -- HTML output -------------------------------------------------------------

html_theme = "furo"

# Empty html_title so the sidebar shows the AXIOMM logo alone instead
# of "AXIOMM 0.1.0.dev0" text underneath it. The lockup SVG already
# carries the AXIOMM wordmark, so a separate text title would be
# redundant. html_short_title is also set so browser tabs fall back
# to a clean "AXIOMM — page title" rather than the noisy
# "{project} {release} documentation" default Sphinx would otherwise
# pick.
html_title = ""
html_short_title = "AXIOMM"

# Register the design-identity folder as a static path so Sphinx copies
# the axiomm_wave assets into `_static/` at build time. Furo resolves
# `light_logo` / `dark_logo` *relative to `_static/`*, so without this
# step the generated HTML produces broken `_static/../identy/...` URLs
# that 404 on the deployed site.
html_static_path = ["../identy/AXIOMM_Design"]

# Favicon: tab-bar icon for the published docs. Unlike Furo's
# `light_logo` / `dark_logo` (which are resolved relative to
# `_static/`), Sphinx looks for `html_favicon` relative to the
# configuration directory — so we point at the source file directly
# here. Sphinx still copies it into `_static/` at build time.
html_favicon = "../identy/AXIOMM_Design/axiomm_wave_icon_dark.svg"

html_theme_options = {
    "source_repository": "https://github.com/FrancescoPerrone/axiomm/",
    "source_branch": "main",
    "source_directory": "docs/",
    # Furo: paths are resolved relative to `_static/`. Both variants
    # are in the identity folder we registered above, so the bare
    # filename is enough.
    #
    # Light mode uses the *lockup* (icon + AXIOMM wordmark) so the
    # sidebar's primary brand element is fully readable. The previous
    # icon-only light variant (`axiomm_wave_icon.svg`) rendered
    # incorrectly on the deployed Pages site; the lockup is the
    # canonical light-mode mark anyway.
    "light_logo": "axiomm_wave_lockup.svg",
    # Dark mode keeps the dark icon — the wordmark in the dark
    # lockup's stroke colour can read poorly on Furo's dark surface,
    # and the icon-only mark is a clean fallback there.
    "dark_logo": "axiomm_wave_icon_dark.svg",
}


# -- MyST (Markdown) ---------------------------------------------------------

myst_enable_extensions = [
    "deflist",
    "tasklist",
    "colon_fence",
    "dollarmath",      # $...$ for inline math
    "amsmath",         # \begin{align} ... \end{align}
    "fieldlist",
    "substitution",
]

myst_heading_anchors = 4  # add anchors to headings up to level 4


# -- Intersphinx -------------------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "h5py": ("https://docs.h5py.org/en/stable/", None),
    "hyperspy": ("https://hyperspy.org/hyperspy-doc/current/", None),
}


# -- sphinx-autoapi ----------------------------------------------------------

autoapi_type = "python"
autoapi_dirs = [str(_REPO_ROOT / "src" / "axiomm")]
autoapi_root = "api"
autoapi_keep_files = False
autoapi_add_toctree_entry = True
autoapi_options = [
    "members",
    "undoc-members",
    "show-inheritance",
    "show-module-summary",
    "imported-members",
]
# Don't tracebacks from optional-dep imports during autoapi discovery.
suppress_warnings = ["autoapi"]


# -- sphinx-copybutton -------------------------------------------------------

copybutton_prompt_text = r">>> |\$ "
copybutton_prompt_is_regexp = True


# -- Misc --------------------------------------------------------------------

# Nitpicky catches broken cross-references; useful while authoring.
nitpicky = False  # flip to True once references stabilise.
